### ISSUE TITLE
Error in ProgressBar when running the detect.py

### ISSUE THREAD

**Issue by Sugar-Coder** [feiyuhuahuo/Yolact_minimal#19]
Hi, I want to use the detect.py to cut out some images. But when I was running:
`python detect.py --weight=weights/best_29.3_res50_coco_400001.pth --image=images ` 
I got:
```
Model loaded with weights/best_29.3_res50_coco_400001.pth.

Traceback (most recent call last):
  File "detect.py", line 57, in <module>
    progress_bar = ProgressBar(40, ds)
  File "Yolact_minimal/utils/common_utils.py", line 23, in __init__
    self.update_str()
  File "Yolact_minimal/utils/common_utils.py", line 26, in update_str
    num_bars = int(self.length * (self.cur_val / self.max_val))
ZeroDivisionError: division by zero
```
I check the line 56 in detect.py, it seems that the length of data_loader is zero.
I'm new to pytorch. Can you help me? Thanks!

**Comment by feiyuhuahuo** [comment]
Please check if there are images under the `Yolact_minimal/images` folder,  and note that these images should be .jpg images.

**Comment by Sugar-Coder** [comment]
Thanks for reply. 
But there is the ``Yolact_minimal/images`` folder and a ``person.jpeg`` image in it. When I changed the image's name to ``person.jpg``.  I got the differrent error:
```
...
Model loaded with weights/best_29.3_res50_coco_400001.pth.

[W ParallelNative.cpp:206] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
[W ParallelNative.cpp:206] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
[W ParallelNative.cpp:206] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
[W ParallelNative.cpp:206] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
  File "~/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "~/anaconda3/envs/yolact-env/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "~/anaconda3/envs/yolact-env/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "~/anaconda3/envs/yolact-env/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "~/anaconda3/envs/yolact-env/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "~/anaconda3/envs/yolact-env/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "~/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 14156) is killed by signal: Segmentation fault: 11. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "detect.py", line 60, in <module>
    for i, (img, img_origin, img_name) in enumerate(data_loader):
  File "~/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "~/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "~/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1034, in _get_data
    success, data = self._try_get_data()
  File "~/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 885, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 14156) exited unexpectedly

```
What should I do?

**Comment by feiyuhuahuo** [comment]
https://github.com/feiyuhuahuo/Yolact_minimal/blob/b89e88c782b7499b8d4e3f04366f2ef10545eec4/detect.py#L54
Try to set `num_workers` to 0, your CPU seems to support few threads.

**Comment by Sugar-Coder** [comment]
That works! Thank you very much😄
