### ISSUE TITLE
Some question about detecting video by detect.py

### ISSUE THREAD

**Issue by zgh199710** [feiyuhuahuo/Yolact_minimal#21]
Hi!
When I run detect by using my weight that Trained by my own dataset,  I meet this wrong message:

Traceback (most recent call last):
  File "/home/zgh/Yolact_minimal-master/detect.py", line 124, in <module>
    frame_trans = val_aug(frame_origin, cfg)
  File "/home/zgh/Yolact_minimal-master/utils/augmentations.py", line 221, in val_aug
    img = multi_scale_resize(img, resize_range=val_size, during_training=False)
  File "/home/zgh/Yolact_minimal-master/utils/augmentations.py", line 188, in multi_scale_resize
    return cv2.resize(img, (resize_range, resize_range))
TypeError: an integer is required (got type res101_custom)

More: I detected some images and no problem.  Thank you for your great project!

**Comment by feiyuhuahuo** [comment]
It's a bug I ignored. Check the latest commit, it's OK now.

**Comment by zgh199710** [comment]
Thanks! amigo
