### ISSUE TITLE
How could I train my own dataset on swin-tiny? 

### ISSUE THREAD

**Issue by zgh199710** [feiyuhuahuo/Yolact_minimal#25]
I changed the config.py but get error on pre-weight
That is error:
 Traceback (most recent call last):
  File "train.py", line 51, in <module>
    assert re.findall(r'res.+_[a-z]+', args.resume)[0] == cfg_name, 'Resume weight is not compatible with current cfg.'
IndexError: list index out of range
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    assert re.findall(r'res.+_[a-z]+', args.resume)[0] == cfg_name, 'Resume weight is not compatible with current cfg.'
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/zhsy-zgh/anaconda3/envs/yolact/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zhsy-zgh/anaconda3/envs/yolact/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhsy-zgh/anaconda3/envs/yolact/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/zhsy-zgh/anaconda3/envs/yolact/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zhsy-zgh/anaconda3/envs/yolact/bin/python', '-u', 'train.py', '--local_rank=2', '--resume=model/swin_tiny.pth']' returned non-zero exit status 1.

**Comment by zgh199710** [comment]
Oh, I should use python -m torch.distributed.launch --nproc_per_node=1 --master_port=$((RANDOM)) train.py --cfg=res101_custom It's running!

**Comment by abhigoku10** [comment]
@zgh199710  did u train the model on the swin transformer how are the results and speed can you please share ur sample results
