### ISSUE TITLE
detec.py出错，出错信息如下

### ISSUE THREAD

**Issue by clannadcl** [feiyuhuahuo/Yolact_minimal#32]
Traceback (most recent call last):                                                                                                                                    
  File "detect.py", line 73, in <module>                                                                                                                              
    ids_p, class_p, box_p, coef_p, proto_p = nms(class_p, box_p, coef_p, proto_p, net.anchors, cfg)                                                                   
  File "/root/paddlejob/workspace/env_run/video_tag/code/yolact/utils/output_utils.py", line 153, in nms                                                              
    box_thre = torch.clip(box_thre, min=0., max=1.)                                                                                                                   
AttributeError: module 'torch' has no attribute 'clip'

**Comment by feiyuhuahuo** [comment]
What is your PyTorch version?

**Comment by JianJingGao** [comment]
@feiyuhuahuo i have same error,pytorch 1.6

**Comment by JianJingGao** [comment]
change version to pytorch 1.9, i's ok

**Comment by Zhang-Jing-Xuan** [comment]
Don't need to change the version of pytorch.
Just change
```python
box_thre = torch.clip(box_thre, min=0., max=1.)
```
to
```python
box_thre = torch.clamp(box_thre, min=0., max=1.) # pytorch 1.5.0
```
or to
```python
tmp = np.clip(box_thre.cpu().numpy(),a_min=0., a_max=1.) # numpy 1.21.1
box_thre =torch.from_numpy(tmp).cuda()
# box_thre = torch.clip(box_thre, min=0., max=1.)
```
