### ISSUE TITLE
Hi， Would you please tell me how to train custom datasets with background?

### ISSUE THREAD

**Issue by Byronnar** [feiyuhuahuo/Yolact_minimal#34]
When I add background class in train.json with Segmentation is [], the error occured as below:
```
Traceback (most recent call last):
  File "train_pizza.py", line 85, in <module>
    for images, targets, masks in train_data_loader:    # 开始训练
  File "/home/byronnar/anaconda3/envs/dev/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/byronnar/anaconda3/envs/dev/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/byronnar/anaconda3/envs/dev/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/byronnar/anaconda3/envs/dev/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/c/Users/MLT/Desktop/projects/instance_segmentation/yolact_onnx_parser_trt/utils/coco.py", line 90, in __getitem__
    if bbox[0] < 0 or bbox[1] < 0 or bbox[2] < 4 or bbox[3] < 4:
IndexError: list index out of range
```
How should I modify? Thank you!

**Comment by feiyuhuahuo** [comment]
What do you mean you add the background class? And what do you mean `segmentation is []`?

**Comment by Byronnar** [comment]
> What do you mean you add the background class? And what do you mean `segmentation is []`?

Yes, my train.json  annotations part as below:
```
{
		"id": 4,
		"image_id": 3,
		"category_id": 0,
		"segmentation": [],
		"area": 0,
		"bbox": [],
		"iscrowd": 0
```
this image not include the useful object so "segmentation" is [], but I can not train.

**Comment by feiyuhuahuo** [comment]
Instance segmentation models need both segmentation annotation and box annotation to train.  If some of your images does not contain any object, these images should not be trained.

**Comment by Byronnar** [comment]
> Instance segmentation models need both segmentation annotation and box annotation to train. If some of your images does not contain any object, these images should not be trained.

Ok，thank you!
