### ISSUE TITLE
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError

### ISSUE THREAD

**Issue by Darshvino** [feiyuhuahuo/Yolact_minimal#46]
Hi @feiyuhuahuo,

Thanks for your great work. 

I am training Yoloact_minimal with Custom Annotation format and modified Dataloader. But whenever the training gets started, then I am facing issue as **_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError**. I do not have clue on why the issue is coming and what is causing.

I am attaching the detailed trace below:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError

```

Can you please assist me in solving the issue. Would be a great help from your side.

Looking forward to your reply.

Thanks.

**Comment by Darshvino** [comment]
Solved by upgrading the NumPy version to 1.19.5
