### ISSUE TITLE
RuntimeError: 'path' must be None or a list, not <class '_frozen_importlib_external._NamespacePath'>

### ISSUE THREAD

**Issue by DL-Alva** [feiyuhuahuo/Yolact_minimal#6]
Hi, thank you for your project.But when I run "python train.py --config=res101_custom_config", it occurs:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 888, in _find_spec
AttributeError: 'PyxImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from eval import evaluate
  File "/Users/liukaijun/lkj项目/小样本检测/5_Yolact的最小复现/eval.py", line 18, in <module>
    from utils.output_utils import after_nms, NMS
  File "/Users/liukaijun/lkj项目/小样本检测/5_Yolact的最小复现/utils/output_utils.py", line 13, in <module>
    from utils.cython_nms import nms as cnms
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 890, in _find_spec
  File "<frozen importlib._bootstrap>", line 864, in _find_spec_legacy
  File "/Users/liukaijun/anaconda3/lib/python3.6/site-packages/pyximport/pyximport.py", line 253, in find_module
    fp, pathname, (ext,mode,ty) = imp.find_module(fullname,package_path)
  File "/Users/liukaijun/anaconda3/lib/python3.6/imp.py", line 271, in find_module
    "not {}".format(type(path)))
RuntimeError: 'path' must be None or a list, not <class '_frozen_importlib_external._NamespacePath'>

Sorry for troubling you, and do you know how to solve with it?

**Comment by feiyuhuahuo** [comment]
Line 13 in output_utils.py is used for traditional_nms. If you don't need traditional_nms, you can directly comment that line and the related code for traditional_nms.
Or try to reinstall Cython, I'm not sure. Because pyximport comes from Cython.

**Comment by mychina75** [comment]
I tried to upgrade cython and solved the issue.
